# Over de data set
# Bron: https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset
#
# Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues. 
# Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.
#
# Attribute Information:
# - instant: record index 
# - dteday : date 
# - season : season (1:springer, 2:summer, 3:fall, 4:winter) 
# - yr : year (0: 2011, 1:2012) 
# - mnth : month ( 1 to 12) 
# - holiday : weather day is holiday or not (extracted from [Web Link]) 
# - weekday : day of the week 
# - workingday : if day is neither weekend nor holiday is 1, otherwise is 0. 
# + weathersit : 
# - 1: Clear, Few clouds, Partly cloudy, Partly cloudy 
# - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist 
# - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds 
# - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog 
# - temp : Normalized temperature in Celsius. The values are divided to 41 (max) 
# - atemp: Normalized feeling temperature in Celsius. The values are divided to 50 (max) 
# - hum: Normalized humidity. The values are divided to 100 (max) 
# - windspeed: Normalized wind speed. The values are divided to 67 (max) 
# - casual: count of casual users 
# - registered: count of registered users 
# - cnt: count of total rental bikes including both casual and registered

###### Voorbereiding ######

# Installeer de benodigde packages
install.packages("ggplot2")
install.packages("GGally")
install.packages("gridExtra")
library(GGally)
library(ggplot2)
library(gridExtra)

# Functie van Machine Learning Lab.
mae <- function (actual, predicted) {
	lengte <- length(actual);
	if ( lengte != length(predicted) ) {
		stop("Length of actual and predicted values must be equal!");
	}
	
	som <- 0;
	for (i in 1:lengte) {
		som <- som + abs( actual[i] - predicted[i] );
	}
	return ( som / lengte );
}

##### Start Lab ######

# 1.0 Data inlezen

# 1.1 Verkennen van de dataset

# 1.2 Verrijken van de dataset.

# 2.0 Zoeken naar correlaties (1/2)

# 2.1 Zoeken naar correlaties (2/2)

# 3.0 Distributie

# 3.1 Distributie schaal

# 3.2 Distributie density

# 4.0 Correlaties onderzoeken

# 4.1 Correlaties onderzoeken met ggpairs

# 4.2 Correlaties plotten

# 4.3 Correlaties plotten met ggplot

# 4.4 Plot uitbreiden

# 4.5 Plot nog verder uitbreiden

# 5.0 Onderzoek distributie

# 5.1 Verbeterde boxplot

# 5.2 Overview boxplot

# 5.3 Mediaan plotten

# 6.0 Regressiemodel bouwen

# 6.1 Resultaten regressiemodel

# 6.2 Diagnose regressiemodel (1/2)

# 6.3 Diagnose regressiemodel (2/2)

# 6.4 Een beter model

# 6.5 Diagnose regressiemodel

# 6.6 Controle uitschieter

# 7.0 Resultaat

##### Einde Lab ######

